### ISSUE TITLE
Differences with Equilab and other equity calculators

### ISSUE THREAD

**Issue by mattmcegg** [mitpokerbots/pbots_calc#3]
Cross checking the equity calculations from this app vs other industry standards like Power Equilab and PokerStove returns different/unexpected differences in calculation.

For example: A simple check of QQ+ vs TT+ should give hero with QQ+ 65% equity.

This repo gives me:
<img width="1280" alt="Screen Shot 2020-12-22 at 7 31 09 PM" src="https://user-images.githubusercontent.com/479110/102948855-7725ac80-448c-11eb-9454-cc66ff4babef.png">

However, Equilab returns:
<img width="1221" alt="Screen Shot 2020-12-22 at 7 33 03 PM" src="https://user-images.githubusercontent.com/479110/102948887-886eb900-448c-11eb-85b1-378359c57172.png">

While it may not seem like a huge difference, I am just trying to figure out why? 

Is it something to do with card removal?

You can also check results on https://app.omni.poker/#/equity

**Comment by david-amirault** [comment]
This repo is not actively maintained and has not been for many years. If you put up a PR, I will happily accept it. But no active debugging of the code will happen from our side.

**Comment by mattmcegg** [comment]
It was more of a question really. Not asking for any changes.
